name: Run Spotify Loginer

on:
  schedule:
    - cron: "0 0 */13 * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Chrome
        run: |
          choco install googlechrome -y
          choco install chromedriver -y

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          SPOTIFY_USERNAME: ${{ secrets.SPOTIFY_USERNAME }}
          SPOTIFY_PASSWORD: ${{ secrets.SPOTIFY_PASSWORD }}
        run: python spotify_loginer.py -u ${{ secrets.SPOTIFY_USERNAME }} -p ${{ secrets.SPOTIFY_PASSWORD }}
